title: Ollie and Mango's Awesome Adventure
subtitle: A blog about traveling with adventure cats.
author: William Harkcom
email: your-email@domain.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image_path: "/assets/img/posts"

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: wharkcom # replace with your_instagram_username or comment to remove link from footer
facebook_username: William.Harkcom
social:
  name: William Harkcom
  links:
    - https://www.facebook.com/William.Harkcom
    # - https://www.linkedin.com/in/BenBalter
    # - https://plus.google.com/+BenBalter
    # - https://github.com/benbalter
    # - https://keybase.io/benbalter
    
google_tag_manager: GTM-5JDH493
maps:
  google:
    api_key: AIzaSyBf0W1mqSatygIi57oxnliRIOlu933aNVU

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-maps
